fix: allow marketplace version update without any existing version
If the marketplace listing doesn't have a version yet, do allow to
create a new version request.
This fixes:

File "awspub/image_marketplace.py", line 40, in request_new_version
    for version in entity["DetailsDocument"]["Versions"]:
                   ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'Versions'